SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) FAVORITES
FROM REST_INFO A JOIN
    (
     SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITES
     FROM REST_INFO
     GROUP BY FOOD_TYPE
    ) AS B
    USING(FOOD_TYPE)
WHERE A.FAVORITES=B.MAX_FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC