SELECT 
    A.ID,
    CASE
        WHEN (RN / TOTAL) <= 0.25 THEN 'CRITICAL'
        WHEN (RN / TOTAL) <= 0.5 THEN 'HIGH'
        WHEN (RN / TOTAL) <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM 
    ECOLI_DATA A
JOIN (
    SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN
    FROM ECOLI_DATA
) AS B
ON A.ID=B.ID
JOIN (SELECT COUNT(*) AS TOTAL FROM ECOLI_DATA) AS C
ORDER BY A.ID