SELECT B.FLAVOR
FROM FIRST_HALF A RIGHT JOIN JULY B USING(SHIPMENT_ID)
GROUP BY B.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC
LIMIT 3


# SELECT B.FLAVOR, SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) AS TOTAL
# FROM FIRST_HALF A RIGHT JOIN JULY B USING(SHIPMENT_ID)
# GROUP BY B.FLAVOR

# SELECT FLAVOR
# FROM FIRST_HALF A