SELECT 
    B.EMP_NO,
    B.EMP_NAME,
    CASE
        WHEN AVG(SCORE) < 80 THEN 'C'
        WHEN AVG(SCORE) < 90 THEN 'B'
        WHEN AVG(SCORE) < 96 THEN 'A'
        ELSE 'S'
    END GRADE,
    SAL * CASE
        WHEN AVG(SCORE) < 80 THEN 0
        WHEN AVG(SCORE) < 90 THEN 0.1
        WHEN AVG(SCORE) < 96 THEN 0.15
        ELSE 0.2
    END BONUS
FROM HR_EMPLOYEES B JOIN HR_GRADE C ON B.EMP_NO=C.EMP_NO
GROUP BY B.EMP_NO
ORDER BY B.EMP_NO