SELECT YEAR(DIFFERENTIATION_DATE) YEAR, (B.MAX-A.SIZE_OF_COLONY) YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YR,
            MAX(SIZE_OF_COLONY) AS MAX 
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS B
    ON YEAR(A.DIFFERENTIATION_DATE)=B.YR
ORDER BY 1, 2