SELECT ID, C.FISH_NAME, A.LENGTH
FROM 
    FISH_INFO A 
JOIN
    (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) AS B
ON  A.FISH_TYPE=B.FISH_TYPE AND A.LENGTH=B.MAX_LENGTH
JOIN FISH_NAME_INFO C ON B.FISH_TYPE=C.FISH_TYPE
ORDER BY ID